import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { neueMontreal } from "./ui/fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ 
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${inter.className} bg-[#030708] text-[#eee]` }>
      <nav className="flex flex-row-reverse">
          <ul  >
            <li className={`inline-block mx-10 md:text-nav ${neueMontreal} font-normal`}><a href="#">Home</a></li>
            <li className={`inline-block mx-10 md:text-nav ${neueMontreal} font-normal`}><a href="#">About</a></li>
            <li className={`inline-block mx-10 md:text-nav ${neueMontreal} font-normal`}><a href="#">Contact</a></li>
          </ul>
        </nav>
        {children}
        </body>
    </html>
  );
}
